---
before:
  hooks:
    - go mod download

builds:
  - id: lbot
    main: ./cmd
    binary: lbot
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
     - "7"
    ignore:
      - goos: darwin
        goarch: arm

archives:
  - id: lbot-archive
    name_template: >-
      {{ .ProjectName }}_
      {{- .Tag }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- with .Arm }}v{{ . }}{{ end }}
      {{- with .Mips }}_{{ . }}{{ end }}
      {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    builds:
      - lbot
    files:
      - LICENSE

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^build(\(.+\))?:'
      - '^cd(\(.+\))?:'
      - '^ci(\(.+\))?:'
      - '^cicd(\(.+\))?:'
      - '^docker(\(.+\))?:'
      - '^docs(\(.+\))?:'
      - '^refactor(\(.+\))?:'
      - '^test(\(.+\))?:'
      - Merge pull request
      - Merge branch
      - go mod tidy

dockers:
  - image_templates:
      - docker.io/kuzxnia/loadbot:{{ .Tag }}-amd64
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/amd64

  - image_templates:
      - docker.io/kuzxnia/loadbot:{{ .Tag }}-arm64
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/arm64

docker_manifests:
  - name_template: docker.io/kuzxnia/loadbot:{{ .Tag }}
    image_templates:
      - docker.io/kuzxnia/loadbot:{{ .Tag }}-amd64
      - docker.io/kuzxnia/loadbot:{{ .Tag }}-arm64

brews:
  - repository:
      owner: kuzxnia
      name: homebrew-loadbot
      token: "{{ .Env.PRIVATE_ACCESS_TOKEN }}"
    commit_author:
      name: Kacper Kuźniarski
      email: kacper.kuzniarski@gmail.com
    folder: Formula
    goarm: "7"
    homepage: https://github.com/kuzxnia/loadbot
    description: Workload database driver
    license: Apache-2.0
    test: |
      system "#{bin}/lbot -v"
    install: |-
      bin.install "lbot"
