---
# yamllint disable rule:line-length
name: "Docs"

on:
  push:
    branch:
      - 'master'

jobs:
  docs:
    name: docs
    runs-on: ubuntu-latest
    if: |
      always() &&
      (github.ref == 'refs/heads/master')

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: Publish docs
        run: |
          mkdocs build
          mkdocs gh-deploy --force --no-history --remote-branch docs
