---
name: release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          # to be able to generate the full changelog:
          # https://github.com/goreleaser/goreleaser-action/issues/56#issuecomment-568718162
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version-file: go.mod
      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: kuzxnia
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          # renovate: depName=goreleaser/goreleaser datasource=github-releases
          version: v1.23.0
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
